version: '3.7'

services:
  semaf-service:
    container_name: semaf
    build: .
    ports:
      # The HTTP port
      - "8089:80"
    networks:
      - traefik
    volumes:
      - ${datadir}:/data
      - ./config.py:/usr/src/app/config.py

networks:
  traefik:
    external: true

